-- Insert drug data
INSERT INTO drugs (id, medication_name, generic_name, manufacturer, drug_class, indication, dosage_forms, common_dosages, typical_retail_price, description, side_effects, warnings, active, created_at, updated_at) VALUES
('84314f92-9db4-4d0e-9f27-549a801541b0', 'Ozempic', 'semaglutide', 'Novo Nordisk', 'GLP-1 Receptor Agonist', 'Type 2 diabetes, weight management', 'Pre-filled injection pen', '0.25mg, 0.5mg, 1mg, 2mg weekly', '$800-$1000/month', 'Once-weekly injection that helps control blood sugar and promotes weight loss.', 'Nausea, vomiting, diarrhea', 'Risk of thyroid tumors, pancreatitis', true, now(), now()),
('b6184bdd-c8c6-4ad2-9bd5-2faa85e75370', 'Mounjaro', 'tirzepatide', 'Eli Lilly', 'GLP-1/GIP Receptor Agonist', 'Type 2 diabetes', 'Pre-filled injection pen', '2.5mg-15mg weekly', '$900-$1100/month', 'Dual-action injectable medication for type 2 diabetes.', 'Nausea, diarrhea', 'Risk of thyroid tumors, pancreatitis', true, now(), now()),
('27cbc0db-a4bb-4d0c-a4b7-28937499a6dc', 'Trulicity', 'dulaglutide', 'Eli Lilly', 'GLP-1 Receptor Agonist', 'Type 2 diabetes', 'Pre-filled injection pen', '0.75mg-4.5mg weekly', '$750-$900/month', 'Once-weekly GLP-1 injection for type 2 diabetes.', 'Nausea, diarrhea', 'Risk of thyroid tumors', true, now(), now()),
('cd054e26-9d50-4e38-9a25-b999dcd046ee', 'Jardiance', 'empagliflozin', 'Boehringer Ingelheim', 'SGLT2 Inhibitor', 'Type 2 diabetes, heart failure', 'Tablet', '10mg, 25mg daily', '$500-$650/month', 'Lowers blood sugar by helping kidneys remove glucose.', 'UTIs, increased urination', 'Risk of ketoacidosis', true, now(), now()),
('0083ab8a-831a-42ac-9ba6-ac246495afca', 'Farxiga', 'dapagliflozin', 'AstraZeneca', 'SGLT2 Inhibitor', 'Type 2 diabetes, heart failure', 'Tablet', '5mg, 10mg daily', '$500-$650/month', 'SGLT2 inhibitor for diabetes and heart failure.', 'Yeast infections, UTIs', 'Risk of ketoacidosis', true, now(), now()),
('803430a0-9a67-4c07-9dee-e860da7adaad', 'Lantus', 'insulin glargine', 'Sanofi', 'Long-acting Insulin', 'Type 1 and Type 2 diabetes', 'Vial, pen', 'Individualized', '$250-$400/month', 'Long-acting basal insulin for 24-hour control.', 'Low blood sugar, weight gain', 'Risk of severe hypoglycemia', true, now(), now()),
('944246d1-a55d-4477-88f1-f93e92692e0e', 'Humalog', 'insulin lispro', 'Eli Lilly', 'Rapid-acting Insulin', 'Type 1 and Type 2 diabetes', 'Vial, pen', 'With meals', '$250-$400/month', 'Fast-acting mealtime insulin.', 'Low blood sugar', 'Risk of severe hypoglycemia', true, now(), now()),
('2008c6d8-6e12-4cc3-af23-ec602c7007cc', 'Humira', 'adalimumab', 'AbbVie', 'TNF Blocker', 'Rheumatoid arthritis, psoriasis', 'Injection', '40mg every 2 weeks', '$5000-$6000/month', 'Biologic that blocks TNF to reduce inflammation.', 'Infections, headache', 'Risk of serious infections', true, now(), now()),
('344e1a72-1e27-4cb8-9973-5c5fe4304869', 'Enbrel', 'etanercept', 'Amgen', 'TNF Blocker', 'Rheumatoid arthritis', 'Injection', '50mg weekly', '$5000-$6000/month', 'TNF blocker for autoimmune diseases.', 'Infections, headache', 'Risk of serious infections', true, now(), now()),
('850bb107-924d-4aa0-959a-258c86622cd6', 'Stelara', 'ustekinumab', 'Janssen', 'IL-12/23 Blocker', 'Psoriasis, Crohns disease', 'Injection, IV', '45mg, 90mg q12w', '$20000-$25000/year', 'Biologic blocking IL-12 and IL-23.', 'Infections, headache', 'Risk of serious infections', true, now(), now())
ON CONFLICT (id) DO UPDATE SET
  medication_name = EXCLUDED.medication_name,
  generic_name = EXCLUDED.generic_name,
  updated_at = now();
