/*
  # Insert Sample Programs Data

  1. Data
    - Insert 40+ pharmaceutical assistance programs
    - Cover various program types
    - Link to manufacturers
*/

INSERT INTO programs (program_name, program_type, description, manufacturer, eligibility_criteria, income_requirements, insurance_requirements, discount_details, program_url, phone_number, email, enrollment_process, required_documents, coverage_duration, renewal_required) VALUES
('Ozempic Savings Card', 'copay_card', 'Pay as little as $25 for up to a 3-month supply of Ozempic with commercial insurance.', 'Novo Nordisk', 'Commercial insurance required. Not valid for government insurance. Age 18+.', 'No income limits', 'Commercial insurance required', '$25 for 1, 2, or 3-month supply', 'https://www.ozempic.com/savings-and-resources/savings-card.html', '1-866-310-7549', '', 'Activate savings card online, print or save to mobile device, present at pharmacy.', 'Valid prescription, commercial insurance card', '12 months', true),

('Mounjaro Savings Card', 'copay_card', 'Save on your monthly Mounjaro prescription. Most commercially insured patients pay as little as $25 per prescription.', 'Eli Lilly', 'Must have commercial insurance. Not eligible for government insurance (Medicare, Medicaid, etc.). Age 18+.', 'No income limits', 'Commercial insurance required', 'As low as $25 per month', 'https://www.mounjaro.com/savings-resources', '1-800-545-5979', '', 'Download savings card from website or call to request. Present card at pharmacy with prescription.', 'Valid prescription, commercial insurance card', '12 months', true),

('Trulicity Savings Card', 'copay_card', 'Eligible patients pay as little as $25 per month with commercial insurance.', 'Eli Lilly', 'Commercial insurance coverage required. Not for government insurance.', 'No income limits', 'Commercial insurance required', 'As low as $25 per month', 'https://www.trulicity.com/savings-and-support', '1-800-545-5979', '', 'Register online to receive savings card. Use at participating pharmacies.', 'Prescription, commercial insurance information', '12 months', true),

('Jardiance Savings Card', 'copay_card', 'Eligible patients with commercial insurance may pay as little as $10 per month.', 'Boehringer Ingelheim', 'Must have commercial prescription insurance. Maximum savings apply.', 'No income limits', 'Commercial insurance required', '$10 per 30-day supply', 'https://www.jardiance.com/savings-and-support', '1-866-279-3652', '', 'Download card online and present at pharmacy, or enroll by phone.', 'Valid prescription, insurance card', '12 months', true),

('Sanofi Insulins VALyou Savings Program', 'discount_card', 'Pay no more than $35 per month for Lantus insulin.', 'Sanofi', 'All patients qualify regardless of insurance status.', 'No income limits', 'No insurance required', '$35 per month maximum', 'https://www.lantus.com/savings-resources', '1-866-255-6197', '', 'Download savings card from website. Present at pharmacy.', 'Valid prescription', 'Ongoing', false),

('Lilly Insulin Value Program', 'discount_card', 'Get Humalog for $35 per month regardless of insurance status.', 'Eli Lilly', 'Available to all patients, regardless of insurance.', 'No income limits', 'No insurance required', '$35 per month', 'https://www.lillycares.com', '1-833-808-1234', '', 'Purchase at participating pharmacies with Lilly Insulin Value Program card.', 'Valid prescription', 'Ongoing', false),

('Novo Nordisk Patient Assistance Program', 'patient_assistance', 'Free insulin for eligible uninsured patients.', 'Novo Nordisk', 'Must be uninsured and meet income requirements.', 'Below 400% federal poverty level', 'Must be uninsured', 'Free medication', 'https://www.novocare.com/insulin/my99insulin.html', '1-866-310-7549', '', 'Apply through healthcare provider with income documentation.', 'Prescription, proof of income, uninsured status', '12 months', true),

('Tresiba Savings Card', 'copay_card', 'Pay as little as $25 per prescription with commercial insurance.', 'Novo Nordisk', 'Commercial insurance required.', 'No income limits', 'Commercial insurance required', '$25 per prescription', 'https://www.tresiba.com/savings-and-support.html', '1-844-873-7422', '', 'Activate savings card online. Present at pharmacy.', 'Prescription, commercial insurance', '12 months', true),

('Basaglar Savings Card', 'copay_card', 'Eligible patients pay as little as $35 per month.', 'Eli Lilly', 'Commercial insurance required.', 'No income limits', 'Commercial insurance required', '$35 per month', 'https://www.basaglar.com/savings-support', '1-800-545-5979', '', 'Download savings card online. Use at participating pharmacies.', 'Prescription, insurance card', '12 months', true),

('My$99Insulin Program', 'discount_card', 'Up to 3 vials or 2 packs of pens for $99 per month.', 'Novo Nordisk', 'Available to all cash-paying patients.', 'No income limits', 'No insurance required', '$99 for 30-day supply', 'https://www.novocare.com/insulin/my99insulin.html', '1-866-310-7549', '', 'Purchase at pharmacy with My$99Insulin savings card.', 'Valid prescription', 'Ongoing', false),

('Humira Complete Savings Card', 'copay_card', 'Pay as little as $5 per month with commercial insurance.', 'AbbVie', 'Commercial insurance with Humira coverage required.', 'No income limits', 'Commercial insurance required', '$5 per month', 'https://www.humira.com/humira-complete/cost-and-copay', '1-800-448-6472', '', 'Enroll online to receive savings card. Present at pharmacy.', 'Prescription, commercial insurance information', '12 months', true),

('Enbrel Support Savings Card', 'copay_card', 'Most commercially insured patients pay no more than $5 per month.', 'Amgen', 'Commercial insurance required. Does not cover government insurance.', 'No income limits', 'Commercial insurance required', '$5 per month', 'https://www.enbrel.com/support/enbrel-support-savings-card', '1-888-436-2735', '', 'Sign up online or by phone. Receive card to use at pharmacy.', 'Valid prescription, proof of insurance', '12 months', true),

('Janssen CarePath Savings Program', 'copay_card', 'Eligible patients may pay as little as $5 per dose for Stelara.', 'Janssen', 'Commercial insurance coverage required.', 'No income limits', 'Commercial insurance required', '$5 per dose', 'https://www.stelarainfo.com/cost-and-support', '1-877-227-3728', '', 'Enroll online or call. Use card at specialty pharmacy.', 'Prescription, insurance documentation', '12 months', true),

('Cosentyx Co-pay Card', 'copay_card', 'Pay as little as $0 per month with commercial insurance.', 'Novartis', 'Must have commercial insurance. Not for government plans.', 'No income limits', 'Commercial insurance required', '$0 per month', 'https://www.cosentyx.com/financial-support', '1-844-267-3689', '', 'Register online for co-pay card. Present at pharmacy or infusion center.', 'Prescription, proof of commercial insurance', '12 months', true),

('Taltz Together Savings Card', 'copay_card', 'Eligible patients with commercial insurance pay as little as $25 per month.', 'Eli Lilly', 'Commercial insurance required.', 'No income limits', 'Commercial insurance required', '$25 per month', 'https://www.taltz.com/plaque-psoriasis/taltz-together-support', '1-800-545-5979', '', 'Sign up online for savings card. Present at pharmacy.', 'Valid prescription, insurance information', '12 months', true),

('Skyrizi Complete Savings Card', 'copay_card', 'Pay as little as $5 per dose with qualifying insurance.', 'AbbVie', 'Commercial insurance with Skyrizi coverage required.', 'No income limits', 'Commercial insurance required', '$5 per dose', 'https://www.skyrizi.com/savings-and-support', '1-866-759-7494', '', 'Activate card online. Use at specialty pharmacy or infusion site.', 'Prescription, insurance card', '12 months', true),

('Rinvoq Complete Savings Card', 'copay_card', 'Most patients with commercial insurance pay $5 per month.', 'AbbVie', 'Commercial insurance required. Not valid for government insurance.', 'No income limits', 'Commercial insurance required', '$5 per month', 'https://www.rinvoq.com/savings-and-support', '1-866-759-7694', '', 'Enroll online. Download savings card to present at pharmacy.', 'Prescription, proof of insurance', '12 months', true),

('Pfizer Savings Program', 'copay_card', 'Eligible patients pay as little as $0 per month for Xeljanz.', 'Pfizer', 'Commercial insurance with Xeljanz coverage. Income restrictions may apply.', 'Income verification required', 'Commercial insurance required', '$0 per month', 'https://www.xeljanz.com/support-savings', '1-844-935-5269', '', 'Apply online or by phone. Receive co-pay card.', 'Prescription, insurance information', '12 months', true),

('Orencia Co-Pay Program', 'copay_card', 'Pay as little as $5 per month with insurance.', 'Bristol Myers Squibb', 'Commercial insurance required.', 'No income limits', 'Commercial insurance required', '$5 per month', 'https://www.orencia.com/support-and-savings/co-pay', '1-800-673-6242', '', 'Enroll through website or call. Use card at pharmacy.', 'Valid prescription, insurance card', '12 months', true),

('Dupixent MyWay Co-pay Card', 'copay_card', 'Pay as little as $0 per prescription with commercial insurance.', 'Sanofi/Regeneron', 'Commercial insurance with Dupixent coverage required.', 'No income limits', 'Commercial insurance required', '$0 per prescription', 'https://www.dupixent.com/myway', '1-844-387-4936', '', 'Register online or by phone. Receive co-pay card for pharmacy use.', 'Prescription, commercial insurance', '12 months', true),

('Eliquis Co-Pay Savings Card', 'copay_card', 'Pay as little as $10 per 30-day supply.', 'Bristol Myers Squibb', 'Commercial insurance required. Maximum savings apply.', 'No income limits', 'Commercial insurance required', '$10 per month', 'https://www.eliquis.bmscustomerconnect.com/copay', '1-855-354-7847', '', 'Activate card online or by phone. Use at pharmacy.', 'Prescription, proof of insurance', '12 months', true),

('Janssen CarePath for Xarelto', 'copay_card', 'Pay as little as $10 per month for Xarelto.', 'Janssen', 'Commercial insurance coverage required.', 'No income limits', 'Commercial insurance required', '$10 per month', 'https://www.xarelto-us.com/patient-resources', '1-888-927-3586', '', 'Enroll online or by phone. Receive savings card.', 'Prescription, insurance information', '12 months', true),

('Entresto Co-pay Savings Card', 'copay_card', 'Eligible patients pay as little as $10 per month.', 'Novartis', 'Commercial insurance with Entresto coverage required.', 'No income limits', 'Commercial insurance required', '$10 per month', 'https://www.entresto.com/heart-failure/treatment-cost', '1-844-368-7378', '', 'Sign up online. Download or request physical card.', 'Prescription, commercial insurance', '12 months', true),

('Repatha Co-Pay Card', 'copay_card', 'Pay as little as $25 per month with commercial insurance.', 'Amgen', 'Commercial insurance required. Not for government plans.', 'No income limits', 'Commercial insurance required', '$25 per month', 'https://www.repatha.com/taking-repatha/cost-support/', '1-844-737-2842', '', 'Enroll online or by phone. Use card at specialty pharmacy.', 'Prescription, insurance documentation', '12 months', true),

('Praluent Co-Pay Savings Card', 'copay_card', 'Pay as little as $25 per month.', 'Sanofi/Regeneron', 'Commercial insurance with Praluent coverage.', 'No income limits', 'Commercial insurance required', '$25 per month', 'https://www.praluent.com/savings-and-support', '1-844-772-5836', '', 'Register online. Receive savings card for pharmacy use.', 'Valid prescription, insurance card', '12 months', true),

('Boehringer Ingelheim Cares Foundation', 'patient_assistance', 'Free medication for eligible uninsured patients including Spiriva.', 'Boehringer Ingelheim', 'Uninsured and income below 200% of federal poverty level.', 'Below 200% federal poverty level', 'Must be uninsured', 'Free medication', 'https://www.bipatientassistance.com', '1-800-556-8317', '', 'Complete application with healthcare provider. Mail with required documents.', 'Prescription, proof of income, uninsured status', '12 months', true),

('AZ&Me Prescription Savings Program', 'patient_assistance', 'Free Symbicort and other AstraZeneca medications for eligible patients.', 'AstraZeneca', 'Uninsured patients meeting income requirements.', 'Below 400% federal poverty level', 'Must be uninsured', 'Free medication', 'https://www.azandmeapp.com', '1-800-292-6363', '', 'Apply online or by mail with healthcare provider.', 'Application form, prescription, income verification', '12 months', true),

('GSK For You Patient Assistance Program', 'patient_assistance', 'Free Advair and other GSK medications for qualifying uninsured patients.', 'GSK', 'Must be uninsured and meet income guidelines.', 'Below 400% federal poverty level', 'Must be uninsured', 'Free medication', 'https://www.gskforyou.com', '1-866-728-4368', '', 'Complete application with doctor. Submit income documentation.', 'Application, prescription, proof of income', '12 months', true),

('GSK For You Savings Card', 'copay_card', 'Pay as little as $10 per month for Trelegy with commercial insurance.', 'GSK', 'Commercial insurance with Trelegy coverage.', 'No income limits', 'Commercial insurance required', '$10 per month', 'https://www.trelegy.com/savings-and-support.html', '1-888-825-5249', '', 'Register for savings card online. Present at pharmacy.', 'Prescription, insurance card', '12 months', true),

('AZ&Me Prescription Savings for Fasenra', 'copay_card', 'Up to $3,000 in annual savings on Fasenra.', 'AstraZeneca', 'Commercial insurance or cash-paying patients. Income limits apply.', 'Income verification may apply', 'Commercial insurance or self-pay', 'Up to $3,000/year', 'https://www.fasenra.com/savings-and-support.html', '1-833-327-3672', '', 'Apply online or call. Receive savings card after approval.', 'Prescription, proof of income, insurance info', '12 months', true),

('GSK For You Savings Card for Nucala', 'copay_card', 'Pay as little as $0 per dose with commercial insurance.', 'GSK', 'Commercial insurance coverage required.', 'No income limits', 'Commercial insurance required', '$0 per dose', 'https://www.nucala.com/savings-card/', '1-844-625-2782', '', 'Download savings card online. Use at specialty pharmacy.', 'Prescription, insurance documentation', '12 months', true),

('Merck Patient Assistance Program', 'patient_assistance', 'Free Januvia for eligible patients without insurance.', 'Merck', 'Uninsured and income below 400% of federal poverty level.', 'Below 400% federal poverty level', 'Must be uninsured', 'Free medication', 'https://www.merckhelps.com', '1-800-727-5400', '', 'Complete application with doctor. Submit financial documentation.', 'Application form, prescription, income proof', '12 months', true),

('Victoza Savings Card', 'copay_card', 'Pay as little as $25 per prescription with commercial insurance.', 'Novo Nordisk', 'Commercial insurance required. Age 18+.', 'No income limits', 'Commercial insurance required', '$25 per prescription', 'https://www.victoza.com/savings-and-support.html', '1-877-484-2869', '', 'Activate savings card online. Present at pharmacy with prescription.', 'Prescription, commercial insurance card', '12 months', true),

('Rybelsus Savings Card', 'copay_card', 'Pay as little as $10 per 30-day supply with insurance.', 'Novo Nordisk', 'Commercial insurance required. Not for government plans.', 'No income limits', 'Commercial insurance required', '$10 per month', 'https://www.rybelsus.com/savings-and-coverage.html', '1-877-304-6855', '', 'Activate card online or by phone. Use at pharmacy.', 'Prescription, commercial insurance', '12 months', true),

('AZ&Me Prescription Savings for Bydureon', 'copay_card', 'Savings on Bydureon for eligible patients.', 'AstraZeneca', 'Commercial insurance or meet income requirements.', 'Income verification may apply', 'Commercial insurance or self-pay', 'Varies', 'https://www.bydureon.com/savings-support.html', '1-800-236-9933', '', 'Apply online or by phone. Receive co-pay card.', 'Prescription, insurance or income information', '12 months', true),

('Pfizer Savings Program for Lyrica', 'copay_card', 'Save on out-of-pocket costs for Lyrica.', 'Pfizer', 'Commercial insurance required.', 'No income limits', 'Commercial insurance required', 'Varies by plan', 'https://www.lyrica.com/savings-support', '1-855-459-7422', '', 'Enroll online or by phone. Download savings card.', 'Prescription, insurance card', '12 months', true),

('Lilly Cares Foundation', 'patient_assistance', 'Free Cymbalta and other Lilly medications for eligible uninsured patients.', 'Eli Lilly', 'Must be uninsured and meet income requirements.', 'Below 400% federal poverty level', 'Must be uninsured', 'Free medication', 'https://www.lillycares.com', '1-800-545-6962', '', 'Apply through healthcare provider. Submit financial documentation.', 'Application, prescription, proof of income', '12 months', true),

('Pfizer Patient Assistance Program', 'patient_assistance', 'Free Chantix and other Pfizer medications for eligible patients.', 'Pfizer', 'Uninsured and income below 500% of federal poverty level.', 'Below 500% federal poverty level', 'Must be uninsured', 'Free medication', 'https://www.pfizerpatientassistance.com', '1-844-989-7284', '', 'Complete application with doctor. Mail with required documents.', 'Application, prescription, income verification', '12 months', true),

('Farxiga Savings Card', 'copay_card', 'Save on Farxiga with commercial insurance.', 'AstraZeneca', 'Commercial insurance required.', 'No income limits', 'Commercial insurance required', 'Varies by plan', 'https://www.farxiga.com/savings-and-support.html', '1-844-327-9421', '', 'Apply online for savings card. Present at pharmacy.', 'Prescription, proof of insurance', '12 months', true),

('Janssen CarePath for Invokana', 'copay_card', 'Eligible patients may pay as little as $5 per month.', 'Janssen', 'Must have commercial insurance coverage for Invokana.', 'No income limits', 'Commercial insurance required', '$5 per month', 'https://www.invokanahcp.com/patient-support', '1-877-227-3728', '', 'Enroll through website or phone. Use card at pharmacy.', 'Prescription, insurance information', '12 months', true);
